### ISSUE TITLE
ToPyObject vs IntoPyObject

### ISSUE THREAD

**Issue by m-ou-se** [fusion-engineering/inline-python#10]
We should probably use `IntoPyObject` instead. Right now we're using `ToPyObject`, which will clone data. But we should first investigate if there are any downsides.

**Comment by de-vri-es** [comment]
Are there really many objects that can benefit from `IntoPyObject`? I imagine most things will need to copy their data anyway. It's also a waste to consume something from the rust scope if the data is still getting copied.
