### ISSUE TITLE
Support for calling rust fn?

### ISSUE THREAD

**Issue by benjaminmcdonald** [fusion-engineering/inline-python#12]
```rust
#[pyfunction]
/// Formats the sum of two numbers as string
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}
```

**Comment by de-vri-es** [comment]
It's not clear to me what you're asking for. Is the function body supposed to be Python code? Because it just looks like Rust to me.

**Comment by xavier83** [comment]
Looks like he just pasted the code from https://github.com/PyO3/pyo3#using-rust-from-python

**Comment by de-vri-es** [comment]
Ah, in that case: The intent of this crate is not to duplicate functionality from `pyo3`, but only to easily embed snippets of python from rust.

To make python bindings for a rust library, you should just use `pyo3` directly.

If we're missing the point of the question, feel free to comment and we can re-open the issue.

**Comment by m-ou-se** [comment]
I suppose the issue is that right now it's not easy to call a `#[pyfunction]` from inline `python!{}` code. Sounds like a useful feature. Otherwise you'll have to compile your module to a shared library separately, and then `import` it again in `python!{}`.

**Comment by de-vri-es** [comment]
Although you could ask why you would want to in the first place, considering there is a Rust API already.

Granted, getting data back to Rust isn't super pretty right now, but if we fix that I'm not sure this would still matter.

**Comment by m-ou-se** [comment]
This is now possible using [`Context::add_wrapped`](https://docs.rs/inline-python/0.5.1/inline_python/struct.Context.html#method.add_wrapped).
