### ISSUE TITLE
Dependency on libpython3.7m.so

### ISSUE THREAD

**Issue by Recognition2** [fusion-engineering/inline-python#14]
Recently python 3.8 has been released. After updating my system, python3.7 is no longer available, as can be expected.
Is there a hard dependency on python3.7?
The file libpython3.7m.so no longer exists on the system.
![image](https://user-images.githubusercontent.com/9716052/68933136-502e7e80-0794-11ea-973e-fe4e08fe9aea.png)

I'm currently running Archlinux with python3.8 and inline-python 0.3.2.

**Comment by de-vri-es** [comment]
The dependency on `libpython` is handled by `pyo3`. But my guess is that you may just need to rebuild after the update. Could you try a `cargo clean && cargo build`, see if that helps?

**Comment by de-vri-es** [comment]
I can build on Arch Linux with python 3.8, so I'm assuming a `cargo clean` would fix the problem. If not, and the problem still persists, please comment here I'll re-open the issue :)

**Comment by Recognition2** [comment]
Yup this works, apologies for crying wolf and thanks for the help!
