### ISSUE TITLE
How to return value to Rust

### ISSUE THREAD

**Issue by hyousef-rusty** [fusion-engineering/inline-python#17]
I wrote the below:
```rust
#![feature(proc_macro_hygiene)]
use inline_python::python;

fn main() {
    println!("Hello, Rust!");
    let max = 10;
    let mut z = 0;

    python! {
        import cv2

        print("Hello, Python")
        print(cv2.__version__)
        for x in range(1, 'max, 1):
            print(x)
        'z = 'max
    }
    println!("z = {}", z);
}
```

The variable `max` is sent correctly from Rust to Python, but the variable `z` is not modified in the Python code, it remains zero!

![image](https://user-images.githubusercontent.com/60115476/77233446-776ce080-6bb8-11ea-935a-076d4238b70b.png)

**Comment by de-vri-es** [comment]
The syntax `'var` only allows you to use Rust values from Python, not vice-versa.

Retrieving values back from python is shorty described in the readme:

> ### Getting information back
>
> A Context object could also be used to pass information back to Rust, as you can retrieve the global Python variables from the context through Context::get_global.

More information can be found in the documentation for the [`Context`](https://docs.rs/inline-python/0.4.0/inline_python/struct.Context.html) struct.
