### ISSUE TITLE
Can I load python file inside context

### ISSUE THREAD

**Issue by hyousef-rusty** [fusion-engineering/inline-python#24]
Instead of writting:
```rust
	c.run(python! {
		x = 123
		print("python: x =", x)
		rust_print(x)
	});
```
Can I write something like:
```rust
	c.run(python! {
		load_python_file("file.py")
	});
```
Where "file.py" is:
```python
x = 123
print("python: x =", x)
rust_print(x)
```

**Comment by m-ou-se** [comment]
If you want to know how to load Python files from Python code, check the Python documentation. That's not related to `inline-python`.

**Comment by hyousef-rusty** [comment]
I tried like this:
```rust
c.run(python!  {
                    from fox import load
                    load()
                })
```
tried saving my `fox.py` file at the root directory, as well as at the `src` directory, but in both cases I got: 
```bash
  File "src\main.rs", line 41, in <module>
    from fox import load
ModuleNotFoundError: No module named 'fox'
```
So not sure what is the correct location to save the file in!

**Comment by m-ou-se** [comment]
You'll need to add the path in `sys.path` in Python.
