### ISSUE TITLE
Can I define Context as global

### ISSUE THREAD

**Issue by hyousef-rusty** [fusion-engineering/inline-python#25]
It happened that I need to use the context in multiple Rust function, so I thought to define it as global one like this:
```rust
static c: Context = Context::new();
```

But I got the below error:
```bash
error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
  --> src\main.rs:20:21
   |
20 | static c: Context = Context::new();
   |                     ^^^^^^^^^^^^^^
```

**Comment by de-vri-es** [comment]
No, this isn't possible. Note that a `Context` holds the GIL, so with a static context it would never be released.

**Comment by de-vri-es** [comment]
Actually, that isn't true, it doesn't hold the GIL. You do need to acquire the GIL to create a context though, so this still isn't possible in a `const fn`.
