### ISSUE TITLE
Is it possible to run the python code in a virtualenv?

### ISSUE THREAD

**Issue by m4dcoder** [fusion-engineering/inline-python#34]
For example, if I have a python virtualenv setup on my system with specific requirements installed. Can I configure the inline python to run script using modules installed in that virtualenv?

**Comment by m-ou-se** [comment]
Activating the virtual environment as usual and then running your Rust program in it should work.

**Comment by m4dcoder** [comment]
Thank you for the information and quick response!

**Comment by m4dcoder** [comment]
I tried on ubuntu and was able to use a module installed in a python venv.
