### ISSUE TITLE
Switch to pyo3 0.11 and stable Rust

### ISSUE THREAD

**Issue by paulirotta** [fusion-engineering/inline-python#36]
Projects using inline-python are currently stuck in nightly. pyo3 0.11 add support for stable.

After some sniffing it doesn't look like too much to update. Perhaps 3 changes in `inline-python/macros` and whatever else appears after that.

Nightly Rust has been causing some persistent difficulties for me unrelated to the project. I could try to help with this transition, but confess Python is not something I know much about.

I love the structure of `inline-python` with `Context` and a direct interface without too many details. It would be a bit painful to have to drop back to `pyo3` to solve unrelated project needs.

Any timeline for this update?

**Comment by m-ou-se** [comment]
Yes, we should update to PyO3 0.11. But that doesn't make this crate work on stable just yet. We still need `#![feature(proc_macro_span)]` to reconstruct the whitespace of the Python code.

**Comment by paulirotta** [comment]
Ahh. I missed that. I thought the proc-macro crate was stable, but only tested with default features on it

**Comment by m-ou-se** [comment]
I've updated the crates to use PyO3 0.11, and published them to crates.io.

`inline-python` on stable Rust will have to wait for the `proc_macro_span` feature.

**Comment by paulirotta** [comment]
Excellent! Using it now, and huge thanks from all of us for your efforts.

I checked and it looks like `proc_macro_span` is approaching the end of development phase so I'll hang on with the annoyances of nightly Rust which are less than the pleasures of `inline-python`.
