### ISSUE TITLE
Upgrade to newer PyO3.

### ISSUE THREAD

**Issue by m-ou-se** [fusion-engineering/inline-python#41]
We're stuck at PyO3 0.11 because https://github.com/PyO3/pyo3/pull/1143 breaks `wrap_pyfunction!()` for us. See https://github.com/PyO3/pyo3/pull/1597

Once that fix is merged and published, we can update to the latest PyO3 again.

**Comment by jam1garner** [comment]
@m-ou-se I believe this is fixed by 2506a36?

**Comment by m-ou-se** [comment]
Yes, thanks!
