### ISSUE TITLE
`inline-python-macros` does not compile with certain nightly Rust versions

### ISSUE THREAD

**Issue by m-ou-se** [fusion-engineering/inline-python#62]
The unstable Rust feature `proc_macro_span` that `inline-python` uses was changed, causing breakage. This is expected when using unstable Rust features. :)

`inline-python-macros` 0.11 only compiles with nightly-2023-06-27 or earlier.

`inline-python-macros` 0.12 only compiles with nightly-2023-06-28 or later.

**Comment by gauteh** [comment]
Hi,

I am currently getting an error:

```
error[E0463]: can't find crate for `inline_python_macros`
   --> /home/gauteh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/inline-python-0.12.0/src/lib.rs:138:9
    |
138 | pub use inline_python_macros::python;
    |         ^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `inline-python` (lib) due to previous error

```

with the latest three nightly versions (back to and including 2023-07-22). With 2023-06-28 I am getting a bunch of:

```
   Compiling inline-python-macros v0.12.0
error[E0599]: no method named `line` found for struct `proc_macro::Span` in the current scope
  --> /home/gauteh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/inline-python-macros-0.12.0/src/embed_python.rs:57:35
   |
57 |             self.add_whitespace(span, span.line(), span.column())?;
   |                                            ^^^^ method not found in `Span`


```

**Comment by m-ou-se** [comment]
I can't seem to reproduce that issue. It works fine here with both the latest nightly and with 2023-07-22.

**Comment by gauteh** [comment]
Thank you for checking. Could it be some cargo bug? Or platform? I'm on linux unknown gnu 64 bit.

```
❯ cargo -V
cargo 1.73.0-nightly (7ac9416d8 2023-07-24)
```

**Comment by keltia** [comment]
Still happening now, see #65.
rustc 1.78.0-nightly (bccb9bbb4 2024-02-16)
